title: My Personal Website
email: your-email@example.com
description: >- 
  This is my personal website built with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://galen015.github.io" # the base hostname & protocol for your site
theme: minima # or any other theme you want to use
